### ISSUE TITLE
template: layout:6: missing value for block clause

### ISSUE THREAD

**Issue by go2run** [arschles/go-in-5-minutes#121]
I am sorry to bother you my friend. But I can run episode 5.
Maybe I missed something.

➜  episode5 git:(master) ✗ ./episode5
panic: template: layout:6: missing value for block clause

goroutine 1 [running]:
panic(0x38cfc0, 0xc42000d710)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
html/template.Must(0x0, 0x59ff60, 0xc42000d710, 0x0)
	/usr/local/go/src/html/template/template.go:340 +0x66
github.com/unrolled/render.(*Render).compileTemplatesFromDir.func1(0xc4200c8c80, 0x15, 0x5a7020, 0xc42013c000, 0x0, 0x0, 0x0, 0x0)
	/Users/go2run/code/go/src/github.com/unrolled/render/render.go:196 +0x39e
path/filepath.walk(0xc4200c8c80, 0x15, 0x5a7020, 0xc42013c000, 0xc4200c8a80, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0x3fd8dc, 0x9, 0x5a7020, 0xc420071930, 0xc4200c8a80, 0x0, 0x1)
	/usr/local/go/src/path/filepath/path.go:376 +0x344
path/filepath.Walk(0x3fd8dc, 0x9, 0xc4200c8a80, 0xc42004d9b8, 0xc420019500)
	/usr/local/go/src/path/filepath/path.go:398 +0xd5
github.com/unrolled/render.(*Render).compileTemplatesFromDir(0xc42000a800)
	/Users/go2run/code/go/src/github.com/unrolled/render/render.go:201 +0x300
github.com/unrolled/render.(*Render).compileTemplates(0xc42000a800)
	/Users/go2run/code/go/src/github.com/unrolled/render/render.go:149 +0x3d
github.com/unrolled/render.New(0xc42004dd40, 0x1, 0x1, 0x0)
	/Users/go2run/code/go/src/github.com/unrolled/render/render.go:124 +0x1f0
github.com/arschles/go-in-5-minutes/episode5/handlers.NewRenderRenderer(0x3fd8dc, 0x9, 0xc42000d580, 0x1, 0x1, 0x5c46a8, 0x1, 0x1, 0x1, 0xc42001a0b8)
	/Users/go2run/code/go/src/github.com/arschles/go-in-5-minutes/episode5/handlers/renderer.go:36 +0x130
main.main()
	/Users/go2run/code/go/src/github.com/arschles/go-in-5-minutes/episode5/main.go:31 +0x1b1

layout.html line 6 is 
  {{block "css"}}

**Comment by arschles** [comment]
Hey @go2run - thanks for the bug report. I'll look into this as soon as I can.

**Comment by arschles** [comment]
... and I'll update here with a fix!

**Comment by kdosburn** [comment]
Hi! Has there been a fix? I'm having this same issue :)

**Comment by arschles** [comment]
Hi @kdosburn and @go2run so sorry for the delay!

I wasn't able to reproduce the issue. A few questions to help me out:

1. Did you execute `./episode5` from inside the `episode5` directory?
1. Does this panic only happen for a specific path?

**Comment by arschles** [comment]
Also, I just checked in https://github.com/arschles/go-in-5-minutes/pull/161. It adds the `vendor` directory for episode 5, so try that out on the off chance that a dependency affects this problem (I don't expect that it would)
